### ISSUE TITLE
Icons off Center - Dragonflight

### ISSUE THREAD

**Issue by Uggers** [ascott18/Masque-Skinner-Blizz-Buffs#3]
Thanks for the most recent fix.

I am having this issue were the icons don't appear to be centered properly however.

See the buffs
![image](https://user-images.githubusercontent.com/6855065/198879637-ed8f003e-af92-4287-9b6c-7f915255e674.png)

 vs what it looks like in Bartender and NOP
![image](https://user-images.githubusercontent.com/6855065/198879654-2bea2981-94e9-4206-b1c4-54b477fd0431.png)

No LUA error is popping up though

**Comment by ascott18** [comment]
What skin is that?

**Comment by Uggers** [comment]
Dream, one of masques bundled ones

**Comment by ascott18** [comment]
Thanks, should be fixed now.

**Comment by Uggers** [comment]
Yup perfect now, many thanks for the quick turn around!
